### PR TITLE
Added MySQL and fixed a small bug with Bind-to-Items

### PR DESCRIPTION
**Pull request by alexandre-tardif**

### CODE REVIEW

**Comment by MistPhizzle** [comment]
How exactly does SQL work? Is there a way to import your current bending data into it? I'm definitely interested.

**Comment by alexandre-tardif** [comment]
Oh snap forgot a command... Was what i wanted to do at first... Expect a command on the official 1.7 release. What SQL will do is instead of using BendingPlayers, It'll use a MySQL database, And the way it is setup it could easily allow me to add SQLLite if reqested.

**Comment by MistPhizzle** [comment]
Thanks for the information. I've been wanting SQL with this for a while.

**Comment by alexandre-tardif** [comment]
No problem

**Comment by alexandre-tardif** [comment]
Alright importing command should be working properly. Thanks for reminding me :P

**Pull request closed without merging**
